#!/usr/bin/perl

# This script will setup an authorized_keys2 file if it is present:
# /usb_sensor/config/chroot_local-includes/etc/ssh/authorized_keys2

# Keep in mind that this is a perl script
# when making adjustments to this script

$user = "sensor";

if (! -e "/home/$user/.ssh/") {
    `mkdir /home/$user/.ssh/`;
    `chown $user:$user /home/$user/.ssh/`;
    `chmod 700 /home/$user/.ssh/`;
}

if (-e "/etc/ssh/authorized_keys") {
    `cp /etc/ssh/authorized_keys /home/$user/.ssh/authorized_keys`;
    `chown $user:$user /home/$user/.ssh/authorized_keys`;
    `chmod 600 /home/$user/.ssh/authorized_keys`;
}
