#!/usr/bin/perl

# Keep in mind that this is a perl script
# when making adjustments to this script

$user = "sensor";

if (! -e "/home/$user/.ssh/") {
    `mkdir /home/$user/.ssh/`;
    `chown $user:$user /home/$user/.ssh/`;
    `chmod 700 /home/$user/.ssh/`;
}

if (-e "/etc/ssh/authorized_keys2") {
    `cp /etc/ssh/authorized_keys2 /home/$user/.ssh/authorized_keys2`;
    `chown $user:$user /home/$user/.ssh/authorized_keys2`;
    `chmod 600 /home/$user/.ssh/authorized_keys2`;
}
