#!/bin/sh

MIRROR="http://ftp.nl.debian.org/debian"
DIST="squeeze"

lb config noauto \
	--debug \
	--verbose \
	--parent-mirror-bootstrap $MIRROR \
	--mirror-bootstrap $MIRROR \
	--binary-images "usb-hdd" \
	--distribution squeeze \
	--bootloader syslinux \
	--mirror-binary $MIRROR \
	--mirror-bootstrap $MIRROR \
	--interactive shell \
	--grub-splash config/binary_syslinux/splash.rle \
	--bootappend-live "persistent quickreboot noautologin ip=frommedia nouser" \
	--bootappend-install "persistent quickreboot noautologin ip=frommedia nouser" \
	"${@}"
