#!/bin/sh
#
# you need live-helper package

MIRROR="http://ftp.nl.debian.org/debian"

lh_config -b usb-hdd -d lenny \
   --mirror-binary $MIRROR --mirror-bootstrap $MIRROR \
   --syslinux-timeout 1

sudo lh_clean
sudo lh_build
